dockergen:
    build: dockergen/
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro

nginx:
    build: web/
    volumes_from:
        - dockergen
    environment:
        VIRTUAL_HOST: hostlist.vcap.me
