dockergen:
    image: hairmare/nginx-proxy-hostlist
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro

nginx:
    image: hairmare/nginx-proxy-hostlist-web
    volumes_from:
        - dockergen
    environment:
        VIRTUAL_HOST: hostlist.vcap.me
